# Font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14

# Performance
sync_to_monitor yes
repaint_delay 10
input_delay 3

# Cursor
cursor_shape block
cursor_blink_interval 0

# Window
remember_window_size no
confirm_os_window_close 0
enable_audio_bell no

# Scrolling
scrollback_lines 10000
wheel_scroll_multiplier 5.0

# Padding
window_padding_width 0

# Opacity
background_opacity 0.7

# Clipboard
copy_on_select yes

# Mouse
mouse_hide_wait 0

# Shell
shell zsh
